---
  - name: "SCRIPT ANSIBLE PARA ATUALIZAÇÂO REMOTA DOS REPOSITÓRIOS"
    hosts: servidor

    #########################
    ## VARAIAVEIS DE IMPUT ##
    #########################

    gather_facts: false
    vars_prompt:
      - name: git_user
        prompt: Usuario do GitLab
      - name: git_pass
        prompt: Senha ou Token do GitLab

    ## VARIAVEIS A SEREM MODIFICADAS PELO USUÁRIO ##
    vars:
      - destdir: /var/www
      - projectname: datahub-fastapi
      - host_user: vagrant
      - dependencias: ['docker', 'python3', 'postgresql', ]

    ########################
    ## TAREFAS EXECUTADAS ##
    ########################
    tasks:
      ## CASO HAJA DEPENDECÊNCIAS A SEREM INSTALADAS NO SERVIDOR ##
      - name: "INSTALANDO DEPENDENCIAS CASO HAJA"
        apt:
          name: "{{ dependencias }}"
          state: latest
        become: yes

      ## BAIXANDO ATUALIZAÇÃO DO REPOSITORIO ##
      - name: "EFETUANDO PULL DO REPOSITÓRIO GITLAB DTI"
        become: yes
        git:
          repo: "http://{{git_user}}:{{git_pass}}@git.palmas.to.gov.br/dti-desenvolvimento/{{projectname}}.git"
          dest: '{{destdir}}/{{projectname}}'

      - name: "ALTERANDO OWNER DO PROJETO PARA USER LOCAL"
        become: yes
        file:
          path: '{{destdir}}'
          state: directory
          recurse: yes
          owner: "{{host_user}}"
          group: "{{host_user}}"

      ## PARANDO CONTAINER EM EXECUÇÂO DO PROJETO ##
      - name: "PARANDO CONTAINER ATUAL"
        community.docker.docker_compose:
          project_src: "{{destdir}}/{{projectname}}/Dockerfiles"
          state: absent
        register: dck_output
      ####

      ## SUBINDO NOVAMENTE O SERVIDOR LOGS DISPONIVEIS NO ARQUIVO SELECIONADO ##
      - name: "CRIANDO UMA NOVA IMAGEM DO PROJETO ATUALIZADO"
        community.docker.docker_compose:
          project_name: '{{projectname}}'
          project_src: "{{destdir}}/{{projectname}}/Dockerfiles/"
        register: dck_output

      - name: "Debug Docker"
        ansible.builtin.debug:
          var: dck_output
      ##
        