---
- name: "Playbook para atualização remota do projeto em docker"
  hosts: servidores
  vars_files:
    - external_vars.yml
  gather_facts: false
  vars_prompt:
    - name: git_user
      prompt: Usuario do GitLab
    - name: git_pass
      prompt: Senha ou Token do GitLab
    - name: server_type
      prompt: Tipo de projeto ("docker", "uvicorn")
  roles:
    - { role: roles/checkup-role}
    - { role: roles/docker-role, when: server_type == "docker" }
    - { role: roles/uvicorn-role, when: server_type == "uvicorn" }